yarnPath: .yarn/releases/yarn-4.13.0.cjs
nodeLinker: node-modules

packageExtensions:
  "@prisma/client@*":
    peerDependencies:
      ".prisma": "*"
    peerDependenciesMeta:
      ".prisma":
        optional: true
