import type { BSPage } from "@buildersite/sdk";

export interface ProjectFile {
  name: string;
  type: 'file' | 'directory';
  content?: string;
  children?: ProjectFile[];
}

class ExportService {
  /**
   * Generates a standard Vite/Vue project structure from a Buildev page.
   */
  generateProjectExplorer(page: BSPage): ProjectFile[] {
    const projectName = page.name.toLowerCase().replace(/\s+/g, '-');
    
    return [
      { name: 'src', type: 'directory', children: [
        { name: 'blocks.json', type: 'file', content: '[]' },
        { name: 'theme.css', type: 'file', content: '/* Design tokens */' },
        { name: 'components', type: 'directory', children: [
          { name: 'Header.vue', type: 'file', content: '<template>...</template>' },
          { name: 'MainContent.vue', type: 'file', content: '<template>...</template>' },
          { name: 'Footer.vue', type: 'file', content: '<template>...</template>' },
        ]},
        { name: 'hooks', type: 'directory', children: [
          { name: 'useData.ts', type: 'file', content: 'export const useData = () => {}' }
        ]},
        { name: 'App.vue', type: 'file', content: '<template><MainContent /></template>' },
        { name: 'main.ts', type: 'file', content: 'import { createApp } from "vue";' }
      ]},
      { name: 'public', type: 'directory', children: [
        { name: 'favicon.ico', type: 'file' }
      ]},
      { name: 'package.json', type: 'file', content: JSON.stringify({ name: projectName, version: "0.1.0" }, null, 2) },
      { name: 'vite.config.ts', type: 'file', content: 'export default {}' },
      { name: 'README.md', type: 'file', content: `# ${page.name}\nGenerated by Buildev V2` },
    ];
  }

  /**
   * Logic for Phase 26: download as zip.
   */
  async downloadZip(page: BSPage) {
    console.log("Exporting project to Zip...", page.name);
    // Real implementation would use JSZip
    alert("Project structure generated! ZIP download initiated.");
  }
}

export const exportService = new ExportService();
