import type { BuildevNode, ElementNode, TextNode } from "@buildev/core";
import { stringifyStyles } from "./html";

/**
 * Genera el código de plantilla (template) para un nodo.
 */
function generateTemplate(node: BuildevNode, indent: number = 0): string {
  const spaces = " ".repeat(indent);

  if (node.type === "text") {
    return `${spaces}${(node as TextNode).content}`;
  }

  if (node.type === "element") {
    const element = node as ElementNode;
    const styleStr = element.styles?.base ? ` :style="${JSON.stringify(element.styles.base)}"` : "";
    
    const propsStr = Object.entries(element.props || {})
      .map(([k, v]) => ` ${k}="${v}"`)
      .join("");

    const tag = element.tag || "div";
    const openingTag = `<${tag}${propsStr}${styleStr}>`;
    const closingTag = `</${tag}>`;

    if (!element.children || element.children.length === 0) {
      if (["img", "br", "hr", "input"].includes(tag)) {
        return `${spaces}<${tag}${propsStr}${styleStr} />`;
      }
      return `${spaces}${openingTag}${closingTag}`;
    }

    const childrenHtml = element.children
      .map((child) => generateTemplate(child, indent + 2))
      .join("\n");

    return `${spaces}${openingTag}\n${childrenHtml}\n${spaces}${closingTag}`;
  }

  return "";
}

/**
 * Genera un Single File Component (.vue) completo.
 */
export function generateVueComponent(nodes: BuildevNode[], name: string = "BuildevComponent"): string {
  const template = nodes.map((n) => generateTemplate(n, 2)).join("\n");
  
  return `
<script setup lang="ts">
// Generated by Buildev AI
</script>

<template>
${template}
</template>

<style scoped>
/* Scoped styles can be extracted here in future sprints */
</style>
  `.trim();
}
